#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.aliases

fpath=($fpath ~/functions)
autoload -Uz ~/functions/*

# Created by `pipx` on 2021-05-26 08:41:19
export PATH="$PATH:/home/lamtu/.local/bin"
